import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

import '../lib/core/parser/excel_models.dart';

Future<void> main(List<String> args) async {
  final config = _ToolConfig.fromArgs(args);
  final outputDir = Directory(config.outputDir);
  if (!outputDir.existsSync()) {
    outputDir.createSync(recursive: true);
  }

  if (config.manifestOnly) {
    await _writeManifest(outputDir, config.contentVersion);
    stdout.writeln('Manifest generated in ${outputDir.path}/manifest.json');
    return;
  }

  final reader = _UnsupportedWorkbookReader();
  final sheets = await reader.readWorkbook(config.excelPath);
  await _writeSheetDumps(outputDir, sheets);
  await _writeManifest(outputDir, config.contentVersion);
  stdout.writeln('Excel conversion foundation completed.');
}

Future<void> _writeSheetDumps(Directory outputDir, List<ExcelSheet> sheets) async {
  for (final sheet in sheets) {
    final normalizedFileName = sheet.name
        .trim()
        .replaceAll(RegExp(r'\s+'), '_')
        .replaceAll('/', '_');
    final file = File('${outputDir.path}/$normalizedFileName.json');
    final payload = <String, dynamic>{
      'sheet': sheet.name,
      'headers': sheet.headers,
      'items': sheet.rows,
    };
    await file.writeAsString(
      const JsonEncoder.withIndent('  ').convert(payload),
    );
  }
}

Future<void> _writeManifest(Directory outputDir, String contentVersion) async {
  final files = outputDir
      .listSync()
      .whereType<File>()
      .where((file) => file.path.endsWith('.json'))
      .where((file) => !file.path.endsWith('manifest.json'))
      .toList(growable: false);

  final entries = <Map<String, dynamic>>[];
  for (final file in files) {
    final size = await file.length();
    final checksum = await _sha256ForFile(file);
    entries.add(<String, dynamic>{
      'name': file.uri.pathSegments.last,
      'checksum': 'sha256:$checksum',
      'size': size,
      'required': true,
    });
  }

  final manifest = <String, dynamic>{
    'content_version': contentVersion,
    'generated_at': DateTime.now().toUtc().toIso8601String(),
    'minimum_supported_app_version': '1.0.0',
    'files': entries,
    'notes': 'Generated by tools/excel_to_json.dart foundation',
  };

  final manifestFile = File('${outputDir.path}/manifest.json');
  await manifestFile.writeAsString(const JsonEncoder.withIndent('  ').convert(manifest));
}

Future<String> _sha256ForFile(File file) async {
  final bytes = await file.readAsBytes();
  final digest = sha256.convert(bytes);
  return digest.toString();
}

class _ToolConfig {
  const _ToolConfig({
    required this.excelPath,
    required this.outputDir,
    required this.contentVersion,
    required this.manifestOnly,
  });

  final String excelPath;
  final String outputDir;
  final String contentVersion;
  final bool manifestOnly;

  static _ToolConfig fromArgs(List<String> args) {
    String excelPath = 'تطبيق_الاذكار_معدل.xlsx';
    String outputDir = 'assets/seed';
    String contentVersion = '1.0.0';
    var manifestOnly = false;

    for (var i = 0; i < args.length; i++) {
      final current = args[i];
      if (current == '--excel' && i + 1 < args.length) {
        excelPath = args[++i];
      } else if (current == '--out' && i + 1 < args.length) {
        outputDir = args[++i];
      } else if (current == '--version' && i + 1 < args.length) {
        contentVersion = args[++i];
      } else if (current == '--manifest-only') {
        manifestOnly = true;
      }
    }

    return _ToolConfig(
      excelPath: excelPath,
      outputDir: outputDir,
      contentVersion: contentVersion,
      manifestOnly: manifestOnly,
    );
  }
}

class _UnsupportedWorkbookReader implements ExcelWorkbookReader {
  @override
  Future<List<ExcelSheet>> readWorkbook(String filePath) {
    throw UnsupportedError(
      'Workbook parsing adapter is not wired yet. '
      'Use --manifest-only for now, then add xlsx adapter in next phase.',
    );
  }
}
